api/Controllers/CrudMvcController.cs
using Crud_Api_Assignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization.Json;
using System.Web;
using System.Web.Mvc;

namespace AspWebApi_Crud.Controllers
{
    public class CrudMvcController : Controller
    {
        api_result_dbEntities4 db = new api_result_dbEntities4();
        // GET: CrudMvc
        HttpClient client = new HttpClient();
        public ActionResult Index(String searchString)
        {
            List<Result> repo_list = new List<Result>();
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.GetAsync("CrudApi");
            response.Wait();

            var test = response.Result;

            var res = from m in db.Results
                      select m;
            
            if (!String.IsNullOrEmpty(searchString))
            {
                res = res.Where(model => model.RepositoryName.Contains(searchString));
            }
            return View(res.ToList());   
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Result r)
        {
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.PostAsJsonAsync<Result>("CrudApi", r);
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Create");
        }
        public ActionResult Details(int id)
        {
            Result r = null;
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.GetAsync("CrudApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Result>();
                display.Wait();
                r = display.Result;
            }
            return View(r);
        }
        public ActionResult Edit(int id)
        {
            Result r = null;
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.GetAsync("CrudApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Result>();
                display.Wait();
                r = display.Result;
            }
            return View(r);
        }
        [HttpPost]
        public ActionResult Edit(Result r)
        {
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.PutAsJsonAsync<Result>("CrudApi", r);
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Edit");
        }
        public ActionResult Delete(int id)
        {
            Result r = null;
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.GetAsync("CrudApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                var display = test.Content.ReadAsAsync<Result>();
                display.Wait();
                r = display.Result;
            }
            return View(r);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            client.BaseAddress = new Uri("http://localhost:62685/api/CrudApi");
            var response = client.DeleteAsync("CrudApi/" + id.ToString());
            response.Wait();

            var test = response.Result;
            if (test.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Delete");
        }

        




    }
}

api/Views/CrudMvc/Create.cshtml
@model Crud_Api_Assignment.Models.Result

<center><h3>Create a new Repository</h3></center>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.RepositoryName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RepositoryName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RepositoryName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QueuedAt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QueuedAt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QueuedAt, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ScanningAt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ScanningAt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ScanningAt, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FinishedAt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FinishedAt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FinishedAt, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Findings, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Findings, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Findings, "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

api/Views/CrudMvc/Delete.cshtml
@model Crud_Api_Assignment.Models.Result

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RepositoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RepositoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QueuedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueuedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScanningAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScanningAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Findings)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Findings)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

api/Views/CrudMvc/Details.cshtml
@model Crud_Api_Assignment.Models.Result

<div>
    <h4>Details</h4>
    <hr />
    <dl class="table">

    
        

        <dt>
            @Html.DisplayNameFor(model => model.Findings)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Findings)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

api/Views/CrudMvc/Edit.cshtml
@model Crud_Api_Assignment.Models.Result

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    
    <div class="form-horizontal">
        <h4>Edit the repository details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.RepositoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepositoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepositoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QueuedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QueuedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QueuedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScanningAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ScanningAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ScanningAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinishedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinishedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinishedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Findings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Findings, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Findings, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

api/Views/CrudMvc/Index.cshtml
@model IEnumerable<Crud_Api_Assignment.Models.Result>

<center><h1>Security Scan Result</h1></center>

<p>
    <button>@Html.ActionLink("Create New", "Create")</button>
</p>


<form asp-controller="CrudMvc" asp-action="Search" method="get">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RepositoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QueuedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScanningAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinishedAt)
        </th>


        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RepositoryName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.QueuedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScanningAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishedAt)
            </td>

            <td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>